### ISSUE TITLE
How to define pulse rate variable for AQL queries in ehrscape explorer

### ISSUE THREAD

**Issue by eneimi** [ehrscape/examples#2]
I've been trying to do a vital signs AQL query in the ehrscape explorer, but I keep getting errors while defining the pulse rate variable. Is there a specific mapping I need to use? All the others work - 'blood_pressure', 'body_temperature', 'respirations', but 'pulse' is a no show. In the archetype definition  it reads Pulse/Heart Rate and the data element is Pulse Rate/magnitude. I've tried pulse%20rate, pulse+rate and pulse rate, none works. Help please.
![pulse_aql](https://cloud.githubusercontent.com/assets/17158938/14588140/389da4ae-04c2-11e6-9206-9cf741f64cdb.jpg)

**Comment by freshehr** [comment]
Hi,

It looks as if you are using the Marand Explorer AQL syntax, used to help auto-generate AQL - you should not normally try to enter this manually. You can look at 'canonical' AQL by clicking on the Tidy-up tab.

What happens if you double-click on the Pulse Rate /magnitude node in the right-hand template tree? - that should create the correct Marand Explorer syntax for you. This is fully interchangeable with canonical AQL - just toggle Tidy-up

Ian

![2016-04-17_17-37-26](https://cloud.githubusercontent.com/assets/1325125/14588520/687c5a66-04c3-11e6-91ba-e31c48f91a40.png)

![2016-04-17_17-37-12](https://cloud.githubusercontent.com/assets/1325125/14588525/70f71316-04c3-11e6-8ba6-f7904088809f.png)

**Comment by eneimi** [comment]
Thanks.
I switched to native AQL as in your second example and it worked. I think for some reason it refused to recognize Pulse as a valid archetype.
When I clicked tidy up it gave me: 

> MESSAGE
> 
> Errors during query compilation: (18,5) No archetype for rmType=OBSERVATION, simplePath=Pulse, language=en (8,5) Variable 'p' is not defined

I don't know why because I do have a Pulse archetype imported.
Double clicking the magnitude node didn't do anything. But right clicking did give me the AQL path which was as should be: /items[at0004]/value/magnitude.
Strange.
I guess I'll stick canonical AQL.
Thanks again.

**Comment by freshehr** [comment]
I have found that EhrExplorer works pretty well. It might worth seeing what happens when you switch back from canonical to Explorer AQL - it will try to create Explorer AQL - and see if dpuble-clicking on magnitude works then

**Comment by eneimi** [comment]
If its in canonical form, when I double click it does switch to Explorer AQL. But if in Explorer AQL form double clicking doesn't do anything. 
Toggling 'tidy up' switches between both modes just fine. I'm curious as to why it used Pulse_Rate as data element and Pulse_Heart_beat as archetype id. Looks as if it replaces space with an underscore?
The pulse archetype is from the openEHR CKM. In its definitions, [at0004] is 'Rate', [at1026] is 'Pulse Rate' and [at1027] is 'Heart Rate'. 
The canonical in this query specifies [at0004], but in Explorer AQL it shows up as Pulse_Rate (which I presume is actually equivalent to [at1026]). Or have I gotten things mixed up?
![pulse_aql2](https://cloud.githubusercontent.com/assets/17158938/14589022/77584f8a-04d8-11e6-966b-64eb028bcdf7.jpg)
![pulse_aql3](https://cloud.githubusercontent.com/assets/17158938/14589023/7758b466-04d8-11e6-9b3c-537636042c47.jpg)
![pulse_aql5](https://cloud.githubusercontent.com/assets/17158938/14589143/31eeef5a-04db-11e6-9e77-a3a0f89e9ec0.jpg)

**Comment by eneimi** [comment]
Even when I use the API Explorer to query `https://rest.ehrscape.com/rest/v1/view/{ehrId}/pulse`, I get a code 200, but an empty response body.
![pulse_aql6](https://cloud.githubusercontent.com/assets/17158938/14589207/7076b48c-04dc-11e6-8236-6f1a836ffa3a.jpg)

**Comment by freshehr** [comment]
What Ehrscape domain are you using? It is possible that the /view/pulse API call is using an older version of the pulse archetype than the one you have loaded.

**Comment by eneimi** [comment]
Erm..I'm not sure, the default one I guess, `https://ehrscape.com/api-explorer.html`
For the dev Explorer where I run the AQL queries I'm using my assigned domain, but for the API Explorer I simply access it from that URL and set my login and ehrid details.

**Comment by freshehr** [comment]
I would guess that the /view APIs registered at the ehrscape.com are using an older draft version of the Pulse archetype. /views are generally just wrappers around AQL statements. They are customisable but you need access to the Think!EHR admin service for that (not part of the Ehrscape domain provision).

**Comment by eneimi** [comment]
Sounds the most reasonable thing.
Thanks for clearing things up for me.
I've accomplished what I set out to do but I wonder if I should shutdown this thread or wait for one of the admins to do some kind of update on the APIs?

**Comment by borutf** [comment]
Ian took good care of your question, thanks Ian! 
Some details;

ad #AQL/AQL)
To make AQL more compact & human friendly, EhrExplorer uses #AQL notation.
#AQL are converted to canonical AQL using a TidyUp button. It works also in reverse! (from AQL to #AQL).

ad API Explorer)
API Explorer uses a "default" account. Select the top right button to change the settings and connect to your account & domain.

**Comment by freshehr** [comment]
Hi Fabio,

Can you just clarify if the /view pulse call is perhaps tied to a different version of the Pulse archetype from the one that eneimi is using (current CKM version), which would explain the empty response?

Ian

**Comment by borutf** [comment]
Along with a new domain we create some default templates & compositions.
Vital Signs template uses; openEHR-EHR-OBSERVATION.heart_rate-pulse.v1  
However in the CKM there's openEHR-EHR-OBSERVATION.pulse.v1

Eneimi probably used a Vital Signs saved query, which has a mistake when referencing pulse ;

OBSERVATION p#Pulse  <-- should be replaced with OBSERVATION p#Heart_rate_and_rhythm

I've checked with API Explorer: /view/{ehrId}/pulse
and returns successfully a result set  ...

**Comment by eneimi** [comment]
Yeah, I noticed the existing templates and forms. 
I actually created a new vital signs template which included the pulse.v1 archetype from the CKM and built a new vital signs form as well. At first I tried querying using the existing vital signs query, but then edited it to reflect definitions in the pulse.v1 archetype, but that didn't work as it appears ehrscape interprets some of the data elements in the pulse.v1 differently.
I think for instance the REST API explorer query looks for a 'Rate' data element which exists, but doesn't have a value in my current vital signs template so the query returns empty. But the element 'Pulse Rate' does have a value and in the ehrscape Explorer this is interpreted as 'Pulse_Rate' and does return the correct values.
Perhaps it's just a freak case of a bad blend of different but related archetypes, templates, forms, compositions and queries. But just so you can take a look in case it's something else.

The API explorer query you ran successfully returned results, I presume it's based on heart_rate-pulse.v1? Is it possible to try with a template based on pulse.v1?

**Comment by borutf** [comment]
Yes, blending two nearly identical archetypes usually adds confusion ...  

## The AQL behind the /view/{ehrId}/pulse is;

select
    a_a/data[at0002]/events[at0003]/time/value as time,
    a_a/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude as pulse,
    a_a/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/units as unit
from EHR e
contains OBSERVATION a_a[openEHR-EHR-OBSERVATION.heart_rate-pulse.v1]
...

We can add any view you want ;) as long there's an AQL behind ;)

**Comment by eneimi** [comment]
That's noted.
You were right Ian, I didn't have to do it manually. I eventually figured out double clicking from the tree on the right did add the elements I needed and they were correctly mapped 'automatically' this time.
As for the API explorer,
If I run GET ../pulse as user:guidemo, it works fine but if I run it while logged in to my domain it's a no show.
All other vital sign nodes in my template are returned fine (bp, respirations, temperature) and of course, it happens that the archetypes for these are identical with the ones at the bottom of this page: [https://www.ehrscape.com/gui-examples.html#_flexible_gui_building_blocks](url)
I suppose the call to default
`[openEHR-EHR-OBSERVATION.heart_rate-pulse.v1]`
while my template contains
`[openEHR-EHR-OBSERVATION.pulse.v1]` is the underlying issue.
I guess that figures; if we update archetypes/templates we should be sure to update calls to them in the queries.
Thanks guys.
I'll shut this down.
